heat_template_version: 2013-05-23
description: server member of mypool
parameters:
  name:
    type: string
    description: Nom du serveur avec son index
  image:
    type: string
    description: Image used for servers
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  user_data:
    type: string
    description: Server user_data
  network:
    type: string
    description: Network used by the server

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: {get_param: name}
      flavor: {get_param: flavor}
      image: {get_param: image}
      user_data: {get_param: user_data}
      user_data_format: RAW
      networks: [{network: {get_param: network} }]
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 8080

# outputs:
#   server_ip:
#     description: IP Address of the load-balanced server.
#     value: { get_attr: [server, first_address] }
#   lb_member:
#     description: LB member details.
#     value: { get_attr: [member, show] }